### ISSUE TITLE
Auth support

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/service-client#2]
We need to discuss and find a solution for:
Security

Case: service gets compromised
Currently we allow service2service calls directly without any auth.
This means compromised service could be misused to execute calls triggering privileged data manipulation.
We can avoid by preventing service2service direct calls and accept calls from kong only.

For this we would need two things:
1. make sure service calls to apis are actually originating from kong (out of scope here)
2. support proper authentication with kong in order to call other services (in case we are NOT calling on behalf of user)

The latter case actually could be required in case we need to do a privileged call to do something the current user is not allowed to (e.g. creating auth credentials), or in case that we dont have a user context (which would be the case when executing scheduled tasks or triggered by asynchronous events)

The default case should still be what we have now, i.e. service-client is forwarding user header info that it received (transparent case)
Additionally we should allow calls be made with explicit oauth2 flow to target service via kong, using specifically created credentials for the calling service (this is a user and will use Request Owner Credentials Grant Flow)

**Comment by kwierchris** [comment]
Done.
