### ISSUE TITLE
service role support

### ISSUE THREAD

**Issue by sureshvarman-cronj** [OpusCapita/service-client#3]
we need to have token details for the service (not for the user, for the service itself). Since we have ACL applied by roles.
Auth service will be supporting Resource owner grant flow.
1. service client should cache the service tokens by calling auth service.
2. have to get new token using refresh token before expiration.
3. use service token, in absence of user token.
4. parameter to force use service token.

**Comment by kwierchris** [comment]
Have to check if this is still valid.
